trigger:
- master

pool:
  name: 'New Core'

jobs:
- job: Build
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
      npm run build-storybook
    displayName: 'Install deps & build vite + storybook'

  # Publicar build de Vite
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'dist'
      ArtifactName: 'vite-dist'
      publishLocation: 'Container'

  # Publicar build de Storybook
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'storybook-static'
      ArtifactName: 'storybook-dist'
      publishLocation: 'Container'

  # Publicar Storybook como sitio web
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'storybook-static'
      ArtifactName: 'drop'
      publishLocation: 'Container'

- job: Deploy
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'storybook-static'
      ArtifactName: 'storybook-static'
      publishLocation: 'Container'